/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as CreateVideoRouteImport } from './routes/create.video'
import { Route as CreateUpscaleRouteImport } from './routes/create.upscale'
import { Route as CreateTimelineRouteImport } from './routes/create.timeline'
import { Route as CreateMotionRouteImport } from './routes/create.motion'
import { Route as CreateLipsyncRouteImport } from './routes/create.lipsync'
import { Route as CreateImageEditorRouteImport } from './routes/create.image-editor'
import { Route as CreateImageRouteImport } from './routes/create.image'
import { Route as CreateExtractRouteImport } from './routes/create.extract'
import { Route as CreateElementsRouteImport } from './routes/create.elements'
import { Route as CreateAvatarRouteImport } from './routes/create.avatar'
import { Route as CreateAudioRouteImport } from './routes/create.audio'
import { Route as CreateAgentRouteImport } from './routes/create.agent'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateVideoRoute = CreateVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => CreateRoute,
} as any)
const CreateUpscaleRoute = CreateUpscaleRouteImport.update({
  id: '/upscale',
  path: '/upscale',
  getParentRoute: () => CreateRoute,
} as any)
const CreateTimelineRoute = CreateTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => CreateRoute,
} as any)
const CreateMotionRoute = CreateMotionRouteImport.update({
  id: '/motion',
  path: '/motion',
  getParentRoute: () => CreateRoute,
} as any)
const CreateLipsyncRoute = CreateLipsyncRouteImport.update({
  id: '/lipsync',
  path: '/lipsync',
  getParentRoute: () => CreateRoute,
} as any)
const CreateImageEditorRoute = CreateImageEditorRouteImport.update({
  id: '/image-editor',
  path: '/image-editor',
  getParentRoute: () => CreateRoute,
} as any)
const CreateImageRoute = CreateImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => CreateRoute,
} as any)
const CreateExtractRoute = CreateExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => CreateRoute,
} as any)
const CreateElementsRoute = CreateElementsRouteImport.update({
  id: '/elements',
  path: '/elements',
  getParentRoute: () => CreateRoute,
} as any)
const CreateAvatarRoute = CreateAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => CreateRoute,
} as any)
const CreateAudioRoute = CreateAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => CreateRoute,
} as any)
const CreateAgentRoute = CreateAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => CreateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRouteWithChildren
  '/earn': typeof EarnRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/library': typeof LibraryRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRoute
  '/create/agent': typeof CreateAgentRoute
  '/create/audio': typeof CreateAudioRoute
  '/create/avatar': typeof CreateAvatarRoute
  '/create/elements': typeof CreateElementsRoute
  '/create/extract': typeof CreateExtractRoute
  '/create/image': typeof CreateImageRoute
  '/create/image-editor': typeof CreateImageEditorRoute
  '/create/lipsync': typeof CreateLipsyncRoute
  '/create/motion': typeof CreateMotionRoute
  '/create/timeline': typeof CreateTimelineRoute
  '/create/upscale': typeof CreateUpscaleRoute
  '/create/video': typeof CreateVideoRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRouteWithChildren
  '/earn': typeof EarnRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/library': typeof LibraryRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRoute
  '/create/agent': typeof CreateAgentRoute
  '/create/audio': typeof CreateAudioRoute
  '/create/avatar': typeof CreateAvatarRoute
  '/create/elements': typeof CreateElementsRoute
  '/create/extract': typeof CreateExtractRoute
  '/create/image': typeof CreateImageRoute
  '/create/image-editor': typeof CreateImageEditorRoute
  '/create/lipsync': typeof CreateLipsyncRoute
  '/create/motion': typeof CreateMotionRoute
  '/create/timeline': typeof CreateTimelineRoute
  '/create/upscale': typeof CreateUpscaleRoute
  '/create/video': typeof CreateVideoRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRouteWithChildren
  '/earn': typeof EarnRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/library': typeof LibraryRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRoute
  '/create/agent': typeof CreateAgentRoute
  '/create/audio': typeof CreateAudioRoute
  '/create/avatar': typeof CreateAvatarRoute
  '/create/elements': typeof CreateElementsRoute
  '/create/extract': typeof CreateExtractRoute
  '/create/image': typeof CreateImageRoute
  '/create/image-editor': typeof CreateImageEditorRoute
  '/create/lipsync': typeof CreateLipsyncRoute
  '/create/motion': typeof CreateMotionRoute
  '/create/timeline': typeof CreateTimelineRoute
  '/create/upscale': typeof CreateUpscaleRoute
  '/create/video': typeof CreateVideoRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create'
    | '/earn'
    | '/explore'
    | '/feed'
    | '/library'
    | '/sessions'
    | '/settings'
    | '/sitemap.xml'
    | '/tools'
    | '/create/agent'
    | '/create/audio'
    | '/create/avatar'
    | '/create/elements'
    | '/create/extract'
    | '/create/image'
    | '/create/image-editor'
    | '/create/lipsync'
    | '/create/motion'
    | '/create/timeline'
    | '/create/upscale'
    | '/create/video'
    | '/u/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create'
    | '/earn'
    | '/explore'
    | '/feed'
    | '/library'
    | '/sessions'
    | '/settings'
    | '/sitemap.xml'
    | '/tools'
    | '/create/agent'
    | '/create/audio'
    | '/create/avatar'
    | '/create/elements'
    | '/create/extract'
    | '/create/image'
    | '/create/image-editor'
    | '/create/lipsync'
    | '/create/motion'
    | '/create/timeline'
    | '/create/upscale'
    | '/create/video'
    | '/u/$handle'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/create'
    | '/earn'
    | '/explore'
    | '/feed'
    | '/library'
    | '/sessions'
    | '/settings'
    | '/sitemap.xml'
    | '/tools'
    | '/create/agent'
    | '/create/audio'
    | '/create/avatar'
    | '/create/elements'
    | '/create/extract'
    | '/create/image'
    | '/create/image-editor'
    | '/create/lipsync'
    | '/create/motion'
    | '/create/timeline'
    | '/create/upscale'
    | '/create/video'
    | '/u/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRouteWithChildren
  EarnRoute: typeof EarnRoute
  ExploreRoute: typeof ExploreRoute
  FeedRoute: typeof FeedRoute
  LibraryRoute: typeof LibraryRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToolsRoute: typeof ToolsRoute
  UHandleRoute: typeof UHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/video': {
      id: '/create/video'
      path: '/video'
      fullPath: '/create/video'
      preLoaderRoute: typeof CreateVideoRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/upscale': {
      id: '/create/upscale'
      path: '/upscale'
      fullPath: '/create/upscale'
      preLoaderRoute: typeof CreateUpscaleRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/timeline': {
      id: '/create/timeline'
      path: '/timeline'
      fullPath: '/create/timeline'
      preLoaderRoute: typeof CreateTimelineRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/motion': {
      id: '/create/motion'
      path: '/motion'
      fullPath: '/create/motion'
      preLoaderRoute: typeof CreateMotionRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/lipsync': {
      id: '/create/lipsync'
      path: '/lipsync'
      fullPath: '/create/lipsync'
      preLoaderRoute: typeof CreateLipsyncRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/image-editor': {
      id: '/create/image-editor'
      path: '/image-editor'
      fullPath: '/create/image-editor'
      preLoaderRoute: typeof CreateImageEditorRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/image': {
      id: '/create/image'
      path: '/image'
      fullPath: '/create/image'
      preLoaderRoute: typeof CreateImageRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/extract': {
      id: '/create/extract'
      path: '/extract'
      fullPath: '/create/extract'
      preLoaderRoute: typeof CreateExtractRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/elements': {
      id: '/create/elements'
      path: '/elements'
      fullPath: '/create/elements'
      preLoaderRoute: typeof CreateElementsRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/avatar': {
      id: '/create/avatar'
      path: '/avatar'
      fullPath: '/create/avatar'
      preLoaderRoute: typeof CreateAvatarRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/audio': {
      id: '/create/audio'
      path: '/audio'
      fullPath: '/create/audio'
      preLoaderRoute: typeof CreateAudioRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/agent': {
      id: '/create/agent'
      path: '/agent'
      fullPath: '/create/agent'
      preLoaderRoute: typeof CreateAgentRouteImport
      parentRoute: typeof CreateRoute
    }
  }
}

interface CreateRouteChildren {
  CreateAgentRoute: typeof CreateAgentRoute
  CreateAudioRoute: typeof CreateAudioRoute
  CreateAvatarRoute: typeof CreateAvatarRoute
  CreateElementsRoute: typeof CreateElementsRoute
  CreateExtractRoute: typeof CreateExtractRoute
  CreateImageRoute: typeof CreateImageRoute
  CreateImageEditorRoute: typeof CreateImageEditorRoute
  CreateLipsyncRoute: typeof CreateLipsyncRoute
  CreateMotionRoute: typeof CreateMotionRoute
  CreateTimelineRoute: typeof CreateTimelineRoute
  CreateUpscaleRoute: typeof CreateUpscaleRoute
  CreateVideoRoute: typeof CreateVideoRoute
}

const CreateRouteChildren: CreateRouteChildren = {
  CreateAgentRoute: CreateAgentRoute,
  CreateAudioRoute: CreateAudioRoute,
  CreateAvatarRoute: CreateAvatarRoute,
  CreateElementsRoute: CreateElementsRoute,
  CreateExtractRoute: CreateExtractRoute,
  CreateImageRoute: CreateImageRoute,
  CreateImageEditorRoute: CreateImageEditorRoute,
  CreateLipsyncRoute: CreateLipsyncRoute,
  CreateMotionRoute: CreateMotionRoute,
  CreateTimelineRoute: CreateTimelineRoute,
  CreateUpscaleRoute: CreateUpscaleRoute,
  CreateVideoRoute: CreateVideoRoute,
}

const CreateRouteWithChildren =
  CreateRoute._addFileChildren(CreateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRouteWithChildren,
  EarnRoute: EarnRoute,
  ExploreRoute: ExploreRoute,
  FeedRoute: FeedRoute,
  LibraryRoute: LibraryRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToolsRoute: ToolsRoute,
  UHandleRoute: UHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
